server:
  port:8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://10.155.10.47:4702/library?useUnicode=true&characterEncoding=utf-8
    username : b2b_dev
    password : b2b_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  druid:
    initialSize : 5
    minIdle : 5
    maxActive : 20
    maxWait : 60000
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
    filters : stat,wall,log4j
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.example.domain
